version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 1
    reviewers:
      - shinkansenfinance/engineering
    schedule:
      interval: "weekly"

  - package-ecosystem: "pip"
    directory: "/"
    open-pull-requests-limit: 1
    reviewers:
      - shinkansenfinance/engineering
    schedule:
      interval: "daily"
